spring.application.name=SpringBoot-Actuator-SpringSecurity
server.port = 8002


# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always