spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**

        - id: help-service
          uri: lb://HELP-SERVICE
          predicates:
            - Path=/help/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

        - id: demataccount-service
          uri: lb://DEMATACCOUNT-SERVICE
          predicates:
            - Path=/demat/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

server:
  port: 8989